import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Stage } from "react-pixi-fiber";
import RotatingBunny from "../components/roating/index";
import GraphicsExample from "../components/graphic";
export default function Home() {
  const height = 450;
const width = 600;
const OPTIONS = {
  backgroundColor: 0x1099bb,
  height: height,
  width: width
};
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Stage options={OPTIONS}>
        <RotatingBunny x={width / 2} y={height / 2} />
        <RotatingBunny x={width / 3} y={height / 3} />
        <GraphicsExample  x={250}
    y={200}
    width={300}
    height={200}
    fill={0xFFFF00} />
      </Stage>
      </main>

 
    </div>
  )
}
